before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/docker-devtools.key
  - chmod 600 ~/.ssh/docker-devtools.key
  - echo "$SSH_CONFIG" >> ~/.ssh/config
  - mkdir -p ~/.m2
  - echo "$SETTINGS_XML" >> ~/.m2/settings.xml
  - ssh -o StrictHostKeyChecking=no hit uptime
  - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec 2>/dev/null)
  - echo $VERSION

cache:
  untracked: true

stages:
  - test
  - build
  - deploy_to_non_prod_environments
  - deploy_to_prod_environments

test:
  stage: test
  script:
    - mvn clean test -T3
    - mvn sonar:sonar -Dsonar.host.url=https://sonar.heiwa-it.com -Dsonar.login=$SONAR_CREDENTIALS
  artifacts:
    paths:
      - domain/target/myBank/report.pdf
    expire_in: 1 day
  except:
    - /^validation\/.*$/
    - /^feature\/no-frontend$/
    - demo

build:
  stage: build
  script:
    - echo "Building project with maven"
    - mvn deploy -DskipTests
    - echo $VERSION

deploy to development:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to development"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/DEV/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-dev/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-dev && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\"  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  type: deploy
  environment:
    name: dev
  only:
    - develop

deploy to integration:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to integration"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/INT/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-int/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-int && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\"  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  environment:
      name: integration
  only:
    - develop
  when:
    manual

deploy to moe:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to moe"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/MOE/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-moe/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-moe && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\"  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  environment:
      name: moe
  only:
    - /^release\/.*$/
  when:
    manual

deploy to moa:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to moa"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/MOA/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-moa/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-moa && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\"  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  environment:
      name: moa
  only:
    - /^release\/.*$/
  when:
    manual

deploy to staging:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to staging"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/PPD/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-ppd/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-ppd && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\" org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  environment:
      name: staging
  only:
    - master
  when:
    manual

deploy to production:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to production"
    - URL="https://hesperides.heiwa-it.com/rest/files/applications/MyBank/platforms/PROD/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - ssh hit "cd ~/containers/env-prod/apps/conf && curl \"$URL\" >> MyBack.properties"
    - ssh hit "cd ~/containers/env-prod && docker-compose stop && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\"  org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && docker-compose up -d"
  environment:
      name: production
  only:
    - master
  when:
    manual
