before_script:
########### Prérequis ###########
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/docker-devtools.key
  - chmod 600 ~/.ssh/docker-devtools.key
  - echo "$SSH_CONFIG" >> ~/.ssh/config
  - mkdir -p ~/.m2
  - echo "$SETTINGS_XML" >> ~/.m2/settings.xml
  - ssh -o StrictHostKeyChecking=no hit uptime
  - mkdir -p /opt/apps/conf

  ########### Récupère le numéro de version ###########
  - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec 2>/dev/null)
  - echo $VERSION

  ########### Commandes utilisées dans les jobs ###########
  - CMD_ARTIFACT_DOWNLOAD="mvn -Pnexus -U org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy -Dartifact=com.magier.mybank:exposition:$VERSION:jar -DoutputDirectory=./"
  - CMD_DC_STOP="docker-compose stop"
  - CMD_DC_UP="docker-compose up -d"

cache:
  untracked: true

stages:
  - test
  - build
  - deploy_to_non_prod_environments
  - deploy_to_prod_environments

test:
  stage: test
  script:
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/DEV/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - echo $URL_MYBACK_PROPERTIES
    - rm -f /opt/apps/conf/MyBack.properties && curl $URL_MYBACK_PROPERTIES >> /opt/apps/conf/MyBack.properties
    - mvn clean test
    - mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_CREDENTIALS
  artifacts:
    paths:
      - domain/target/myBank/report.pdf
    expire_in: 1 day
  except:
    - /^validation\/.*$/
    - /^feature\/no-frontend$/
    - demo

build:
  stage: build
  script:
    - echo "Building project with maven"
    - mvn deploy -DskipTests
    - echo $VERSION

deploy to development:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to development"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/DEV/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/DEV/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-dev
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && $CMD_ARTIFACT_DOWNLOAD && $CMD_DC_UP"
  type: deploy
  environment:
    name: dev
  only:
    - develop

deploy to integration:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to integration"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/INT/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/INT/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-int
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && $CMD_ARTIFACT_DOWNLOAD && $CMD_DC_UP"
  environment:
      name: integration
  only:
    - develop
  when:
    manual

deploy to moe:
  stage: deploy_to_non_prod_environments
  script:
    - echo "Deploying artifact to moe"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/MOE/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/MOE/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-moe
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && $CMD_ARTIFACT_DOWNLOAD && $CMD_DC_UP"
  environment:
      name: moe
  only:
    - /^release\/.*$/
  when:
    manual

deploy to moa:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to moa"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/MOA/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/MOA/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-moa
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && $CMD_ARTIFACT_DOWNLOAD && $CMD_DC_UP"
  environment:
      name: moa
  only:
    - /^release\/.*$/
  when:
    manual

deploy to staging:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to staging"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/PPD/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/PPD/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-ppd
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && mvn \"-Pnexus\" \"-U\" org.apache.maven.plugins:maven-dependency-plugin:3.0.1:copy \"-Dartifact=com.magier.mybank:exposition:$VERSION:jar\" \"-DoutputDirectory=./\" && $CMD_DC_UP"
  environment:
      name: staging
  only:
    - master
  when:
    manual

deploy to production:
  stage: deploy_to_prod_environments
  script:
    - echo "Deploying artifact to production"
    - URL_MYBACK_PROPERTIES="$HESPERIDES_BASED_URL/MyBank/platforms/PROD/%23Back/MyBank/1.0/instances/default/MyBank-back?isWorkingCopy=true&template_namespace=modules%23MyBank%231.0%23WORKINGCOPY&simulate=true"
    - URL_BACK_APP_YML="$HESPERIDES_BASED_URL/MyBank/platforms/PROD/%23Back/back-application.yml/1.0/instances/default/application.yml?isWorkingCopy=true&template_namespace=modules%23back-application.yml%231.0%23WORKINGCOPY&simulate=true"
    - ENV_FOLDER=$FOLDER_BASE_ENV-prod
    - ssh hit "cd \"$ENV_FOLDER\"/apps/conf && rm -f * && curl \"$URL_MYBACK_PROPERTIES\" >> MyBack.properties && curl \"$URL_BACK_APP_YML\" >> application.yml"
    - ssh hit "cd \"$ENV_FOLDER\" && $CMD_DC_STOP && cd ./apps/artifacts/ && rm -f *.jar && $CMD_ARTIFACT_DOWNLOAD && $CMD_DC_UP"
  environment:
      name: production
  only:
    - master
  when:
    manual
